server:
  port: 8080

# Spring配置
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://master:3306/zzw_test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info


