server:
  port: 8080

# Spring配置
spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      enabled: true
      post:
        enabled: true
logging:
  level:
    root: info
